"SettingScreen1 As screen.'tabletAutoLayout_HeaderMainFooter_ver1.0'":
    LoadingSpinnerColor: =RGBA(0, 120, 212, 1)

    ScreenContainer1_1 As groupContainer.verticalAutoLayoutContainer:
        DropShadow: =DropShadow.Light
        Height: =Parent.Height
        LayoutAlignItems: =LayoutAlignItems.Stretch
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        RadiusBottomLeft: =4
        RadiusBottomRight: =4
        RadiusTopLeft: =4
        RadiusTopRight: =4
        Width: =Parent.Width
        ZIndex: =1

        HeaderContainer1_1 As groupContainer.horizontalAutoLayoutContainer:
            DropShadow: =DropShadow.Regular
            FillPortions: =0
            Height: =75
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            ZIndex: =1

            Label1_1 As label:
                Align: =Align.Center
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =RGBA(50, 49, 48, 1)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledColor: =RGBA(161, 159, 157, 1)
                FillPortions: =1
                FocusedBorderThickness: =4
                Font: =Font.'Segoe UI'
                FontWeight: =FontWeight.Bold
                Height: =Parent.Height
                Size: =24
                Text: ="GeekGPTBot"
                ZIndex: =1

            "Icon1_2 As icon.'3DPrinting'":
                BorderColor: =RGBA(0, 0, 0, 0)
                Color: =RGBA(0, 120, 212, 1)
                DisabledBorderColor: =RGBA(245, 245, 245, 1)
                DisabledColor: =RGBA(225, 223, 221, 1)
                DisabledFill: =RGBA(0, 0, 0, 0)
                FocusedBorderThickness: =4
                Height: =Parent.Height
                HoverBorderColor: =RGBA(0, 0, 0, 0)
                HoverColor: =RGBA(16, 110, 190, 1)
                HoverFill: =RGBA(0, 0, 0, 0)
                Icon: =Icon.Check
                OnSelect: =Navigate(MessageScreen1, ScreenTransition.Fade)
                PaddingBottom: =15
                PaddingLeft: =15
                PaddingRight: =15
                PaddingTop: =15
                PressedBorderColor: =RGBA(0, 0, 0, 0)
                PressedColor: =RGBA(16, 110, 190, 1)
                PressedFill: =RGBA(0, 0, 0, 0)
                Width: =Parent.Height
                ZIndex: =2

        MainSectionContainer1_1 As groupContainer.verticalAutoLayoutContainer:
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingBottom: =20
            PaddingLeft: =20
            PaddingRight: =20
            PaddingTop: =20
            ZIndex: =2

            Label3 As label:
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =RGBA(50, 49, 48, 1)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledColor: =RGBA(161, 159, 157, 1)
                FocusedBorderThickness: =4
                Font: =Font.'Segoe UI'
                Size: =13
                Text: =$"temperture：{tempertureSlider1.Value/10}"
                Width: =Parent.Width -40
                ZIndex: =1

            tempertureSlider1 As slider:
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Default: =7
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                FocusedBorderThickness: =4
                HandleActiveFill: =RGBA(255, 255, 255, 1)
                HandleFill: =RGBA(255, 255, 255, 1)
                HandleHoverFill: =RGBA(255, 255, 255, 1)
                HoverBorderColor: =RGBA(0, 0, 0, 0)
                Max: =10
                PressedBorderColor: =RGBA(0, 0, 0, 0)
                RailFill: =RGBA(184, 187, 184, 1)
                RailHoverFill: =RGBA(222, 236, 249, 1)
                ValueFill: =RGBA(96, 94, 92, 1)
                ValueHoverFill: =RGBA(0, 120, 212, 1)
                Width: =Parent.Width - 40
                ZIndex: =2

            Label3_1 As label:
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =RGBA(50, 49, 48, 1)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledColor: =RGBA(161, 159, 157, 1)
                FocusedBorderThickness: =4
                Font: =Font.'Segoe UI'
                Size: =13
                Text: =$"max_tokens：{maxtokensSlider1.Value}"
                Width: =Parent.Width -40
                ZIndex: =3

            maxtokensSlider1 As slider:
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Default: =800
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                FocusedBorderThickness: =4
                HandleActiveFill: =RGBA(255, 255, 255, 1)
                HandleFill: =RGBA(255, 255, 255, 1)
                HandleHoverFill: =RGBA(255, 255, 255, 1)
                HoverBorderColor: =RGBA(0, 0, 0, 0)
                Max: =4000
                Min: =400
                PressedBorderColor: =RGBA(0, 0, 0, 0)
                RailFill: =RGBA(184, 187, 184, 1)
                RailHoverFill: =RGBA(222, 236, 249, 1)
                ValueFill: =RGBA(96, 94, 92, 1)
                ValueHoverFill: =RGBA(0, 120, 212, 1)
                Width: =Parent.Width - 40
                ZIndex: =4

            Label3_2 As label:
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =RGBA(50, 49, 48, 1)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledColor: =RGBA(161, 159, 157, 1)
                FocusedBorderThickness: =4
                Font: =Font.'Segoe UI'
                Size: =13
                Text: =
                Width: =Parent.Width -40
                ZIndex: =5

            Label3_3 As label:
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =RGBA(50, 49, 48, 1)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledColor: =RGBA(161, 159, 157, 1)
                FocusedBorderThickness: =4
                Font: =Font.'Segoe UI'
                Size: =13
                Text: ="API Version"
                Width: =Parent.Width -40
                ZIndex: =6

            Dropdown1 As dropdown:
                BorderColor: =RGBA(245, 245, 245, 1)
                ChevronBackground: =RGBA(245, 245, 245, 1)
                ChevronDisabledBackground: =RGBA(242, 242, 241, 0)
                ChevronDisabledFill: =RGBA(161, 159, 157, 1)
                ChevronFill: =RGBA(50, 49, 48, 1)
                ChevronHoverBackground: =RGBA(245, 245, 245, 1)
                ChevronHoverFill: =RGBA(50, 49, 48, 1)
                Color: =RGBA(50, 49, 48, 1)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledColor: =RGBA(161, 159, 157, 1)
                DisabledFill: =RGBA(242, 242, 241, 0)
                Fill: =RGBA(245, 245, 245, 1)
                Font: =Font.'Segoe UI'
                HoverBorderColor: =RGBA(16, 110, 190, 1)
                HoverColor: =RGBA(50, 49, 48, 1)
                HoverFill: =RGBA(245, 245, 245, 1)
                Items: =_apiversion
                PaddingBottom: =5
                PaddingLeft: =12
                PaddingRight: =5
                PaddingTop: =5
                PressedBorderColor: =RGBA(16, 110, 190, 1)
                PressedColor: =RGBA(255, 255, 255, 1)
                PressedFill: =RGBA(0, 120, 212, 1)
                SelectionColor: =RGBA(50, 49, 48, 1)
                SelectionFill: =RGBA(0, 120, 212, 1)
                Size: =13
                Width: =Parent.Width - 40
                ZIndex: =7

        FooterContainer1_1 As groupContainer.horizontalAutoLayoutContainer:
            DropShadow: =DropShadow.Regular
            FillPortions: =0
            Height: =75
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingBottom: =10
            PaddingLeft: =10
            PaddingRight: =10
            PaddingTop: =10
            ZIndex: =3

            Label2 As label:
                Align: =Align.Center
                AutoHeight: =true
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =RGBA(50, 49, 48, 1)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledColor: =RGBA(161, 159, 157, 1)
                FillPortions: =1
                FocusedBorderThickness: =4
                Font: =Font.'Segoe UI'
                Size: =13
                Text: ="設定を行ってください。"
                ZIndex: =1

